### ISSUE TITLE
Validating entries

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/libretro-thumbnails#112]
Would it be worthwhile to go through any given repo and check it against Rob Loach's thumbnail checker (https://github.com/RobLoach/libretro-thumbnails-check) for accurate names to clean up/delete non-valid entries? I know there are some (hacks/translations) that are there for a reason, but I found a few that had misaligned names that don't really have a reason for existing, especially when they're just duplicate art. I've had pull requests where one name is favored over another (USA, Australia) vs (USA) and both entries were not allowed to exist. Thoughts?

**Comment by RobLoach** [comment]
The last update of [libretro-thumbnails-check](https://github.com/RobLoach/libretro-thumbnails-check) was 20 days ago. Always open to help clean them up. One name is favoured over another because we prefer No-Intro, and then Redump.

What do you mean by "any given repo"? The check should be hitting every repo https://github.com/RobLoach/libretro-thumbnails-check/tree/master/out

**Comment by masanasake** [comment]
Here's a better example:
Resident Evil: Code Veronica in gamecube in the master:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/105944840/174797311-88261dc1-b613-41d6-8ec2-b3c7ab7d4a35.png">

I check your file checker:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/105944840/174797408-1ad49194-03b8-4db8-8d91-ef03f4e2bc42.png">

Comparing these two, it looks like the bottom 6 entries could be deleted, because they are likely for a different naming convention, an old name, or a typo that was corrected without these being removed.

**Comment by masanasake** [comment]
@RobLoach would you mind merging some of these open pull requests (3DS, GB, GBC, Gamecube) to aid the process? 😄

**Comment by i30817** [comment]
There are some names that don't come from DATs. Namely i've been for a while adding thumbnails to the Scummvm thumbnail repository with names based on the names that the scummvm GUI menu gives to them (the names that get into the scummvm.ini file). This is convenient for me because i can then use another tool i made to automatically create the .scummvm files and the playlist, with the 'correct' labels (ie, the playlist names get the 'right name' instead of all illegal characters changed to '_' like if you scanned the .scummvm files themselves).

So please don't delete things from the scummvm repo. Well, unless they're obviously no scummvm names, which might be hypocritical of me, but i don't care about whatever scummvm collection is being mined for the names (it's obviously kind of ugly).

**Comment by i30817** [comment]
Also i forgot. Do not delete the 'Convention' where for multidisc games there is a name without the '(Disc X)' token (or for multidisc games that are actually different like Metal Gear Solid and Metal Gear Solid VR Missions, the same except with two different names.

These are for m3u files in the playlist.

**Comment by masanasake** [comment]
Yeah, if it appears like there's a reason why these things exist, I won't touch them; I'm all for hacks and translations having alternate art. It's more of a focus to clean up a lot of these "similar but named slightly different" entries that usually share or have clearly outdated art. Kind of sucks that USA and Europe kind of get lumped together, since there's a lot of PAL art out there that's significantly different that there's no great way to account for with the way things are. I'm probably only going to mess with Nintendo and PS stuff, and I'm sure that'll take so long that everything will have changed or migrated somewhere else by the time I get even close to finished. Planning on starting with 3DS. Any idea why 3DS and most PS2 games aren't recognized at all by Retroarch when scanned? 

I had a suspicion about the multi-disc games that didn't have discs, but they're actually accounted for in the checker; thanks for solving the mystery though. 

I'm glad for the warm reception to the touchups and custom stuff I've submitted; I don't have any actual software but I've become very familiar with MS 3D paint. Often comes down to pixel-by-pixel editing. Equal parts entertaining and masochism.

I'd like to tackle the symbolic link issue, but I'm not entirely sure how it's done. I'm pretty sure it's because I don't use the desktop mode. Any ideas on how to do it properly?

Also thanks for the merges, @RobLoach

**Comment by i30817** [comment]
Although it's best for even my tool if the names/thumbnails are as close to 'complete' as possible, i kind of don't see many problems - there are some because of limitations of the tool - because i created [a tool](https://github.com/i30817/libretrofuzz) to find 'the most similar name' on the thumbnail server and adapt it to the name of the playlist label i actually have.

So i'm cheating. I did notice that i had few ps2 games until i ran this too. I basically suspect that some thumbnail repos aren't exactly following the recent redump .dats or something (there has been a lot of recent changes because they got into their heads to add a (language) token to games). And i have another tool to keep rom names uptodate with the redump/no-intro dats ([rhdndat-rn](https://github.com/i30817/rhdndat)).

So yeah, if i'd blame anything for the 3ds and ps2 it would be 'redump/no intro is changing names'.

Symbolic links unfortunately are only possible in linux by cloning the repo, which is obviously a pain (you can do a shallow clone if you don't plan to go back in history, but it's still a lot of download). And you need to know the linux tools to create symbolic links (i made some extra bash functions to help if you're interested) and git.

**Comment by masanasake** [comment]
I mean just scanning the game files in to make a playlist on retroarch. Literally no 3ds games are automatically recognized, and very few of my ps2 games are. I have very little idea how any of this works within retroarch, but I guess it's some metadata assigned to a given file that will produce a valid name. If I manual scan everything is fine. 

Finished the rename for the 3DS box art; wasn't too bad. Probably much easier in desktop mode; need to look into it.

I've seen where symbolic links are possible in Windows, but how that translates to github is beyond me, and something I haven't spent much time on. Seems like it should be simple. Thanks for the link. I'll mess around with it and see if I can't get it figured out.

@RobLoach any word on merging jaffacakelover's work in for GBA?

**Comment by i30817** [comment]
Remember, when you move on to the disc consoles, to be careful to not delete 'orphans' on those lists carelessly, because a bunch of 'orphans' are the m3u versions. For instance i went looking for the ps1 orphan list and i just notice these at random:

Named_Titles/Ace Combat 3 - Electrosphere (Japan).png
Named_Titles/Ace Combat 3 - Electrosphere (Japan, Asia) (Rev 1).png
Named_Titles/Aconcagua (Japan).png

Ace Combat 3 japan version and Aconcagua have two cds, so these 3 are direct translations of the 'normal' games without the (Disc X), using the thumbnails of disc 1 as a symbolic link (or the other way around sometimes). Be careful of what you're deleting when

**Comment by i30817** [comment]
Also obviously, don't delete a symlink source, or if you do, make another the source. This is difficult to tell in windows, but checking the repository online may help you figure out which files are symlinks.

**Comment by i30817** [comment]
> I mean just scanning the game files in to make a playlist on retroarch. Literally no 3ds games are automatically recognized, and very few of my ps2 games are. I have very little idea how any of this works within retroarch, but I guess it's some metadata assigned to a given file that will produce a valid name. If I manual scan everything is fine.

I gave up on the automatic scanner long long ago. Now i just use the manual scanner, and when i want to add or remove games i go to settings->playlists->manage playlists->select one->refresh playlist.

If i want do something different, i do the same then go to the manual scanner again - the act of 'refreshing' the playlist filled the values on that screen, so you can modify those values without remembering everything you did (for instance, if you wanted to scan more than one extension).

**Comment by masanasake** [comment]
Any ideas on (Rev A)? Like what it is and why it's a thing? Doing these symbolic links, I'd love to just remove all traces of (Rev A) them since they don't follow No-intro naming. Thoughts? @i30817

**Comment by i30817** [comment]
rev A, rev B etc, is the alternative of either redump or no intro (i don't remember which one) to '(1.1)'. It's game versions.

Notice that i a very few cases (castlevania symphony of the night iirc, or maybe the japan version), no-intro and redump disagree what version came up first.

**Comment by masanasake** [comment]
Ah. The only instance I've come across is Kid Icarus for NES. Rev A was apparently taken from much later versions, and the difference was how/what passwords were used. Best question is, keep, or remove, since everything for NES and Game boy is No-Intro?

**Comment by i30817** [comment]
If you saw 1.1 numbers in a supposedly no-intro set, it's possible they're changing their mind. The rev convention was always longer than it had to be, so it's possible (recently no intro has been adding (En) language tags - like redump, so it's possible they changed that too i guess).

**Comment by i30817** [comment]
I edited the link to link to all dats (warning: 50mb download) instead of just the commodore amiga dat.

**Comment by masanasake** [comment]
Yeah, haven't come across 1.1 or other any other decimals, just Rev A and very rarely Rev B. About 95% sure that they all came from people requesting them/adding them in by hand, because at some point in time, Retroarch would auto scan the files in under Rev A instead of Rev 1. Trying to get a consensus before trying to remove them. I think things change so frequently and this has been going on so long that it's probably worth it to just try removing them and seeing if someone complains. I'm converting them to symbolic links anyways, so it's not like it would be removing any unique art.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/105944840/175695113-b0ff07a4-856f-4c87-83c1-f0902f372741.png">

**Comment by i30817** [comment]
I'm not a maintainer or anything, but as far as i'm concerned, those can be symlinks, except if the rerelease (which in effect, is what most of the '1.1, 1.2' etc are) has a different cover and the repository recognizes this. Many of these thumbnail repositories don't care about versions and will use the same cover, some do; and some even more yet put in _different covers for languages_.

Deleting them in the other hand, is a bad idea unless they don't actually exist in the source dumps.

**Comment by i30817** [comment]
What actually happens most times outside of the redump sets is that contributers just add the language they 'have' for the game and skip the others. Redump being so wide spread and the console sets being for multiple regions instead of countries makes the language explosion issue more manageable to 5-6 regions instead of 10+ countries.

**Comment by masanasake** [comment]
Yeah, I've seen the different languages and often different box art, and I'm totally fine with it; literally just Rev A and B that's the issue. Powerpuff Girls on GBC is a perfect example:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/105944840/175699248-34e6f4f9-8fa7-4b9a-980d-b34de964b01f.png">

I'm respecting the languages/regions and attributing the symbolic links to the appropriate region base, regardless of whether the art is correct now or not. Just comes down to how many of these Rev A ones have to be made when they're only complicating things. It looks like Rev A only appears in NES and GBC, further begging the question of how it even got started, and if they should be allowed. Just trying to make things as simple and easy as possible, so things can be changed once instead of several times.

**Comment by masanasake** [comment]
Nevermind. I stirred the pot for no reason. The NES ones are valid (I haven't started on NES yet), but there's only 16 GBC ones for obscure titles that aren't valid. Sorry for not checking first. 😅

**Comment by i30817** [comment]
If you're complaining about the images being different and fanmade (like in your mario bros image) you have a point that maybe the images _shouldn't_ be different. There is no value added between a image having a tiny ass 'rev A' or 'rev B' in a corner because retroarch will show the image with the name side by side, and it's just as confusing as not being there because it's so small imo.

**Comment by masanasake** [comment]
Yeah, I was just gonna leave it. I just found it interesting. The quality of those is superb. 

Another interesting tidbit is it looks like No-intro removed Rev A, but it's still found in the NES .rdb file in Retroarch's database folder.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/105944840/175721426-09c6259c-daaa-4ef2-a015-9748590ccb47.png">

Rev A is nowhere to be found for GBC's .rdb. I guess I'll be downloading the standalone Retroarch to see if it's been updated since the Steam version rarely gets updates

**Comment by i30817** [comment]
I'm speculating, but maybe the older ones were inherited dumps from other projects, not the project itself (ie: goodroms renamed), or maybe they're cleaning up for ines2 headers.

It really makes no sense for there being so few alternate versions since it's pretty much the old version of 'oops this had a bug, better send a patch'.

**Comment by i30817** [comment]
I think i know what's happening here. In the zip of no-intro dats i linked above, there are two versions of the dat for the NES, headered and headerless. Discounting the technicality that most emulators can't run headerless nes dumps without breaking, it's natural that the headered version has more variants, because they vary _by header version_ too.

It's quite likely that the 13 Japn 'Rev' you're seeing are those in the unheadered version only, which were verified to change in the cartridge data only, not on a dumper hardware header.

**Comment by i30817** [comment]
I was wrong above - i wasn't searching for '(Rev'... I was searching for '(Rev A' (a significant difference.

You're right, it's kind of weird no-intro has some games using 'Rev A' for '1.1' when it apparently now uses 'Rev 1'.

If i search for just '(Rev' i get:

```
i3@sleipnir:/media/i3/Mordred/Games/dats$ grep "(Rev" Nintendo\ -\ Nintendo\ Entertainment\ System\ \(Header\)\ \(20220618-073730\).dat  | wc -l
Nintendo - Nintendo Entertainment System (Headered) (20220618-073730).dat    Nintendo - Nintendo Entertainment System (Headerless) (20220618-073730).dat
i3@sleipnir:/media/i3/Mordred/Games/dats$ grep "(Rev" Nintendo\ -\ Nintendo\ Entertainment\ System\ \(Headerless\)\ \(20220618-073730\).dat  | wc -l
561
```

If i search for '(Rev [ABCDEF]'  (this is a regex):
```
i3@sleipnir:/media/i3/Mordred/Games/dats$ grep "(Rev [ABCDEF]" Nintendo\ -\ Nintendo\ Entertainment\ System\ \(Headered\)\ \(20220618-073730\).dat  | wc -l
54
i3@sleipnir:/media/i3/Mordred/Games/dats$ grep "(Rev [ABCDEF]" Nintendo\ -\ Nintendo\ Entertainment\ System\ \(Headerless\)\ \(20220618-073730\).dat  | wc -l
54
```

So there is some kind of weird convention clash here. Maybe redump adopted way back when some goodset roms checksums and names and never bothered to rename them because they couldn't verify them?

**Comment by masanasake** [comment]
Well, it's not up to me regardless; just trying to put my near limitless free time to good use. I nixed the GBC ones since it seemed like there's enough evidence to indicate they're just old files. The NES ones I'll leave for now, then do them separately if I get the go ahead. Thanks for looking into it. Hoping to move on to doing symbolic links full-time and padding out the numbers once I get the orphans cleaned up.

**Comment by masanasake** [comment]
So I was thinking about it, and suspicion confirmed: these Rev-A box arts were probably datamined from Nintendo Switch online. Can confirm they're used on NSO.

**Comment by i30817** [comment]
Nintendo canonizing a mistake that now can't get fixed because it's 'canon'. Lol, it reminds of flame wars from fandoms.
