### ISSUE TITLE
PlayStation 2 Tony Hawk's Pro Skater 4 broken links (Both Versions)

### ISSUE THREAD

**Issue by tegaidogun** [libretro-thumbnails/libretro-thumbnails#114]
You can try out this image for a change: 
Original image: https://archive.org/download/tony-hawks-pro-skater-4-ps2-hiresscans/Tony%20Hawk%27s%20Pro%20Skater%204%20-%20Box.jpg

My Personal Cropped image: https://photos.app.goo.gl/cm2bqkj9JgBytEvV6

**Comment by i30817** [comment]
It's another case of the 'replacing a symlink by a file' being broken on the github desktop application.

Anyone with this repository locally can fix it by pulling in a way to make a clean repository (`git pull` followed by `git reset --hard HEAD`, careful this will delete any new local files or commits on the current branch), then checking all the files that were broken symlinks 'changing' to the actual files.

What's wrong is not the file itself, but the git metadata for the file marking it as a symlink, when it actually isn't, because the github application is buggy.

**Comment by i30817** [comment]
So yeah, if you want to use, or replace, symlinks in these repositories, be careful when using the github interface or the github desktop application instead of good old fashioned command line git.

Because it has bugs with replacing symlinks by files.

To avoid the bug you can do commits replacing symlinks in two stages. First delete it, add, then commit, then add the new file. Don't miss one in stage 1 otherwise you get this bug.

**Comment by gerad-not-edgar** [comment]
Was this fixed with https://github.com/libretro-thumbnails/Sony_-_PlayStation_2/pull/37? If so, could you close this issue?
