### ISSUE TITLE
Disable ImgBot?

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#26]
It's great, but can result in larger repos, and possible loss of image quality. Thoughts?

**Comment by alfrix** [comment]
Should not make any difference in quality, but larger repo if you don't keep the repos shallow with --depth=1.
Overall improvement should be around 10%, BUT since i usually compress the images before upload the improvement it's negligible.

Another aproach could be reducing the frequency of updates, i have done it on the DS repo a while ago, because it was updated quite frequently.
https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_DS/blob/master/.imgbotconfig
we could put those in the repos configured monthly.

Or disable it, i feel that it has done quite a lot already.

i'm fine either way.

**Comment by RobLoach** [comment]
Meh!
