### ISSUE TITLE
Update Submodules?

### ISSUE THREAD

**Issue by RobLoach** [libretro-thumbnails/libretro-thumbnails#27]
Would be nice to bring in the latest submodules.

**Comment by alfrix** [comment]
I stopped doing that, since thumbnails.libretro.com and thumbnailpacks.libretro.com grab them directly, and so does:
 `git submodule update --recursive --remote --init`

i didn't see the point in doing it anymore, but if you want i'll do it tommorow...

[PD: i dont even update with that command anymore](https://github.com/alfrix/libretro-thumbnails/blob/master/update_modules.sh)

**Comment by RobLoach** [comment]
:+1:
