### ISSUE TITLE
Nintendo 3DS Titles/Snaps Format

### ISSUE THREAD

**Issue by celerizer** [libretro-thumbnails/libretro-thumbnails#39]
The only current title snap for 3DS shows only the top screen; I don't know of any specific examples but since some games may show relevant info on the bottom screen instead should we cap both for thumbnails? If so, should there be a pixel border between the two screens?

I'd like to start adding small collections of thumbs but we might want to decide on a consistent style.

![image](https://user-images.githubusercontent.com/33245078/46376872-c50c2b00-c65c-11e8-9cb0-5dd11748cd4d.png)

vs.

![image](https://user-images.githubusercontent.com/33245078/46376890-d2c1b080-c65c-11e8-9c31-b3fbda805371.png)

vs.

![image](https://user-images.githubusercontent.com/33245078/46376911-e40abd00-c65c-11e8-9752-086a278659ce.png) (16px separator)

**Comment by RobLoach** [comment]
Not really much space to display them...

![screenshot at 2018-10-02 19-27-12](https://user-images.githubusercontent.com/25086/46382501-3c4fb800-c679-11e8-886e-d5dfd38570fa.png)

**Comment by masanasake** [comment]
I added a ton of them recently, and just used the correct top/bottom ratio to get the whole image (but still leaves the black bars for the bottom screen. I did this for two reasons: 
1. Particularly on regular DS, the title screen would often use both screens; why not have the complete image instead of half?
2. While I'm snapping these by hand within Retroarch, it saves a ton of time from having to crop them.
3.  3DS is still in the very early stages; I think anything goes if it's not replacing anything. Someone can always go back and fix it, but it can't be fixed if nothing is contributed.

@celerizer or @RobLoach would you mind closing this issue?
