### ISSUE TITLE
[Request] Boxarts for Sega Model 1,2,3 and Sega Naomi

### ISSUE THREAD

**Issue by ghost** [libretro-thumbnails/libretro-thumbnails#91]
Requesting boxart thumbnails for the following sega systems.

**Comment by RobLoach** [comment]
What databases do these use?

**Comment by Melon-Bread** [comment]
All 4 of those system are commonly part of the MAME database.

**Comment by Rstation4** [comment]
But Sega Namoi/Atomiswave games are run with a Flycast core. Its a bit confusing because its based on Sega's Dreamcast's hardware.

**Comment by Melon-Bread** [comment]
Yes you can run those with the `flycast` core just as some _Sega Model 1_ games can be used with the `fbneo` core IIRC.  I was just chiming in where I have those games in my collection and what database picks them up.

As for  `NEC - PC-98` there does not seem to be an existing libretro  database. So it may be best to see if there is a good (in the vain of [No-Intro](https://datomatic.no-intro.org/i), [Redump](http://redump.org/), and so on.) data set that can be used within RetroArch and purpose it on the [libretro-database GitHub ](https://github.com/libretro/libretro-database) repo. Since there needs to be a libretro database for thumbnails and such to work proper. So it may be best to move that discussion there.

**Comment by RobLoach** [comment]
For PC-98, added one over at https://github.com/libretro-thumbnails/NEC_-_PC-98

**Comment by Rstation4** [comment]
> For PC-98, added one over at https://github.com/libretro-thumbnails/NEC_-_PC-98

@RobLoach I have thumbnails for other systems/playlists such as the PSP minis, RPG Maker 2000/03, PC-98 and PSX2PSP. How or where can I contribute them. Since i have no permissions to due so I made a few forks and dumped them there.

**Comment by Rstation4** [comment]
@RobLoach can thumbnail contributions be done on my end. Im confused on using github and so far all I did was make a branch repo which I added some PC-98 thumbnails for. As for Database hash algorithms which ones are we supposed to use? Is there any that are getting phased out?

**Comment by RobLoach** [comment]
> can thumbnail contributions be done on my end. Im confused on using github and so far all I did was make a branch repo which I added some PC-98 thumbnails for.

Yes! Click the fork button, and push your changes up to your own fork branch. Following that, github will let you create a Pull Request for it.

![Screenshot at 2021-07-09 12-34-07](https://user-images.githubusercontent.com/25086/125109969-06ee1980-e0b2-11eb-8ec0-39455e93634f.png)

The Github Desktop is really nice, and gives you a user interface around it https://desktop.github.com/

> As for Database hash algorithms which ones are we supposed to use? Is there any that are getting phased out?

We tend to use no-intro primarily, followed by redump for disc media http://redump.org/discs/system/pc-98/

**Comment by Rstation4** [comment]
@RobLoach Thank you, I took some time to look at what you guys did and the changes you did to get a better idea how to integrate a fork I made. For example I created a Atomiswave folder with the folder Named_Boxarts and Named_Snaps along with some thumbnails included for it. Since there was no entries for Atomiswave, Sega Naomi, Sony Playstation Minis I had to fork a master of the main libretro-thumbnails then add the respective folder.

The folders I created for them don't have the arrow, and the numbers used at the end I don't know if they are specifically used from so I made my own based on the system. 19561 = SEGA for example.

As for Dat files, do we still go with crc,sha1 and md5? I wanted to add a dat file for PC-98 Touhou English translated roms.

**Comment by RobLoach** [comment]
CRC, primarily. The rest are nice to have, but not required. Is PC-98 is serial/disc media? Because then it would need the serial associated with it.

**Comment by Rstation4** [comment]
> CRC, primarily. The rest are nice to have, but not required. Is PC-98 is serial/disc media? Because then it would need the serial associated with it.
I'm not sure about that since the formats I have seen mostly are .hdi, I have never seen optical disc media for PC-98 it's usually floppys.

I have question about thumbnail sizes to be used for screenshots folder of Named_Snaps. SInce I have made some on my pc some of them for had been large resolution such as 1920x1080, they don't appear right when I use that in Lakka OS. 
The file sizes so far have been small for them. For example one screenshot from A RPG Maker game came out to be a resolution of 2707x2030 but a small file size of 39.7 kbs. Are those any good? I have since adjusted my screen size to be that of SD definition of 960 × 576.

**Comment by RobLoach** [comment]
> I have question about thumbnail sizes to be used for screenshots folder of Named_Snaps

512 pixels wide... The height is less important, as long as you keep the aspect ratio with 512px wide.

**Comment by Rstation4** [comment]
As for the thumbnails for [Gameboy Advance](https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy_Advance), does that repo allow for more additions? I see the "Sorry, we had to truncate this directory to 1,000 files. 1,066 entries were omitted from the list" message on the page. I was going to add some thumbnails for a rom hack "Mega Moemon FireRed"

**Comment by RobLoach** [comment]
Yeah, the web interface doesn't list them, but they are in there if you clone the repo.

**Comment by masanasake** [comment]
@RobLoach are you able to remove these old issues? Looks like old @ghost isn't with us anymore.
